id: opecha:P001727
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14665
  title: དབུར་སྟོད་འབྲི་གུང་ཉི་ལྕང་བཤད་སྒྲུབ་རབ་རྒྱས་གླིང་གི་ལོ་རྒྱུས་དང་མཁན་པོ་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  volume: ''
  author: ''
