id: P001727
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14665
  title: དབུར་སྟོད་འབྲི་གུང་ཉི་ལྕང་བཤད་སྒྲུབ་རབ་རྒྱས་གླིང་གི་ལོ་རྒྱུས་དང་མཁན་པོ་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    1b6e478deff043a5a30f213ed8feab8d:
      image_group_id: I1KG15748
      title: ''
      volume_number: 1
      total_pages: 434
      base_file: v001.txt
