id: I599CB7C6
legacy_id: P001727
ocr_import_info:
  bdrc_scan_id: W1KG14665
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T16:11:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:11:35.404116+00:00'
last_modified: 2022-08-27 13:12:14.230712
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14665
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14665
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུར་སྟོད་འབྲི་གུང་ཉི་ལྕང་བཤད་སྒྲུབ་རབ་རྒྱས་གླིང་གི་ལོ་རྒྱུས་དང་མཁན་པོ་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: མཁན་པོ་རྟོགས་གྲོལ།
statistics:
  ocr_word_mean_confidence_index: 0.9501515932814898
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG15748:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15748
      total_pages: 434
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15748.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9501515932814898
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
