id: I599CB7C6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:14:08+00:00'
last_modified: '2022-06-07T14:13:13.224115+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14665
  title: དབུར་སྟོད་འབྲི་གུང་ཉི་ལྕང་བཤད་སྒྲུབ་རབ་རྒྱས་གླིང་གི་ལོ་རྒྱུས་དང་མཁན་པོ་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E933:
      image_group_id: I1KG15748
      title: ''
      total_pages: 434
      order: 1
      base_file: E933.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
